<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="data:,">
    <title>예외처리</title>
</head>
<body>
    <h1>try..catch 와 예외처리</h1>
	- 실수, 예상치 못한 사용자 입력,잘못된 서버 응답 등의 이유 발생시 스크립트가 실행이 중단을 방지하기 위한 처리<br>
    - 스크립트 에러가 발생해도 catch에서 에러를 처리하기 때문에 스크립트가 실행이 중단되지 않음.<br>
	- try catch문법 <br>
      - 동작 순서 <br>
      - 1. 먼저 try {} 안의 코드 실행 <br>
      - 2. 에러가 없다면, try 안의 마지막 줄까지 실행, catch 블록은 건너뜀 <br>
      - 3. 에러가 있다면, try 안의 코드의 실행이 중단되고, catch(err) 블록 안 코드 실행<br>
    - error 프로퍼티 종류<br>
      - name: 에러 이름, 정의되지 않은 변수 때문에 발생하는 에러인 경우 ReferenceError가 출력<br>
      - message: 에러 상세 내용을 담고 있는 메시지<br>
      - stack: name : message 형태의 문자열로 출력
    <script type="text/javascript">
    //try-catch 1번 예제
		try {
       // 에러가 발생할 수 있는 코드
      let x = y + 10; // y가 정의되지 않았기 때문에 에러 발생
    } catch (error) {
      // 에러 발생 시 실행되는 코드
      console.log("에러가 발생했습니다: " + error.message);
    }
		
    //try-catch 2번 예제
    try{
      memberName = '123';
      let memberName;
      console.log(memberName);
    }catch(error){
      console.log(error.name);
      console.log(error.message);
      console.log(error.stack);
    }
    </script>


    <h1>try..catch..finally 구문</h1>
    - try catch finally문법 <br>
      - 동작 순서 (finally 구문은 항상실행)<br>
      - 1. 먼저 try {} 안의 코드 실행 <br>
      - 2. 에러가 없다면, try 안의 마지막 줄까지 실행, catch 블록은 건너뜀, finally 블록 실행 <br>
      - 3. 에러가 있다면, try 안의 코드의 실행이 중단되고, catch(err) 블록 안 코드 실행, finally 블록 실행<br>
    <script>
		/**
        try {
			// 예외가 발생될 우려가 있는 코드 집합
		} catch (error) {
			// 예외 처리 (ex: 사용자에게 예외 발생 메시지 알림 etc)
		} finally{
			// 예외가 발생되든 안되든 무조건 코드 실행
		}
		*/
		//양의 정수든 음의 정수든 입력값의 절대값을 반환하는 함수
    const convertAbs = function(intValue){
      if(typeof intValue == 'number' && Number.isInteger(intValue)){
        let result = Math.abs(intValue);
        return result;
      }
      throw new RangeError('입력값은 정수가 아닙니다.');
    }
    try{
      let absInt = convertAbs(-11);
      console.log(absInt);
    }catch(error){
      console.log(error.name);
      console.log(error.message);
      console.log(error.stack);
    }finally{
      console.log('무조건 실행');
    }
    
		
    </script>
</body>
</html>